### PR TITLE
Add helpers to community page

### PR DESCRIPTION
**Pull request by Toaasty778**

### CODE REVIEW

**Review by NightScript370 — COMMENTED** [review]
I disapprove. There's no reason why helpers should be listed here.
Staff should be listed because they should be DMd.

Also, why did you add yourself as a helper?

**Comment by Toaasty778** [comment]
Well cause people like Just Allie work pretty hard keeping the server clean and they deserve an honorable mention

**Comment by Allinxter** [comment]
I appreciate the intention but I think I'll side with NightScript here, the staff is listed in case you need to speak to them directly. I can do nothing if someone is breaking the rules, for example.

And the "honorable mention" is kinda already there? I mean we have our own section on the discord member list.

**Comment by lifehackerhansol** [comment]
I disagree with this as well. Helpers, while a crucial part within the server, are not people that need to be known outside the server. That is not part of the role description.

Staff list is not there for honorable mentions, it is there because it should be known who to contact for issues and whatsoever. 

Closing.

**Pull request closed without merging**
