### PR TITLE
Some small changes to a couple of articles.

### PR DESCRIPTION
**Pull request by Jonatan6**

### CODE REVIEW

**Comment by urmum-69** [comment]
you need java-8-openjfx on arch, not just any version will work
same goes for the jre

**Comment by Jonatan6** [comment]
> you need java8-openjfx on arch, not just any version will work
> same applies for debian, and also the installed jre version 
Alright I changed it 👍

**Comment by puntillol59** [comment]
For the java8 version of JFX on debian, you may need to change the debian command to `sudo apt install openjdk-8-jdk openjfx openjdk-8-jre`

**Comment by urmum-69** [comment]
It seems java 8 is only available in the repositories of debian stretch

**Comment by puntillol59** [comment]
Checked, now it seems now that the only way is to add it from a repo.

**Comment by Jonatan6** [comment]
> Checked, now it seems now that the only way is to add it from a repo.
> 
> Mind if I check for a repo and put installation instructions into a gist?

what ppa is it available on? I cant find seem to find it

**Comment by puntillol59** [comment]
IIRC, adoptopenjdk (https://adoptopenjdk.net/) has a repo for java 8

**Comment by puntillol59** [comment]
I have left instructions here: https://gist.github.com/puntillol59/7532b6583380baca236dcaf2d8f75b5c

**Comment by Jonatan6** [comment]
Thank you. I'll add those to the wiki page then

**Comment by puntillol59** [comment]
Make sure you add the package openjfx after adoptopenjdk-8-hotspot in the last command.

Like this:

`sudo apt install adoptopenjdk-8-hotspot openjfx`

**Comment by Jonatan6** [comment]
noted

**Comment by Jonatan6** [comment]
hmm... I'm not sure if I should add a link to the gist or just put a large code block.

**Comment by puntillol59** [comment]
If you want to link o the gist, I need to update it to include the installation of openJFX

**Comment by Jonatan6** [comment]
yeah, I think thats what I'm gonna do. Can you update the gist?

**Comment by puntillol59** [comment]
Yes, I can.

**Comment by urmum-69** [comment]
With arch, you also must select java 8 as the default jre
there is a provided script, archlinux-java which does this
you run a command like archlinux-java set java-8-openjdk/jre
but honestly I'm not sure trying to maintain such a thing for multiple distributions is worth doing

**Comment by Jonatan6** [comment]
Ok, it gets more and more messy, but I'm gonna add that lol

**Comment by Epicpkmn11** [comment]
Is this ready to be merged?

**Comment by Jonatan6** [comment]
Yes, this is ready to be merged.

**Pull request merged**
